// Fill this file with your personal data. The app consumes this shape.
const data = {
  name: 'K. Mahesh Chandran',
  title: 'Computer Science (AIML) Engineering Student',
  tagline: 'Building surreal products with code, design, and systems thinking.',
  about: `I’m a B.Tech Computer Engineering student at VIT Chennai (2024–2028) with strong depth in frontend engineering, Python systems, and product-driven student innovation. I ship fast, design clean interfaces, and enjoy turning ambitious ideas into working software.`,

  // navigation entries (anchors on the single page)
  nav: [
    { id: 'projects', label: 'Projects' },
    { id: 'skills', label: 'Skills' },
    { id: 'certifications', label: 'Certifications' },
    { id: 'education', label: 'Education' },
    { id: 'contact', label: 'Contact' },
  ],

  // resume link (optional)
  resume: '#',

  // social links
  socials: [
    { name: 'GitHub', href: 'https://github.com/kmahesh110606' },
    { name: 'LinkedIn', href: 'https://linkedin.com/in/kmahesh110606' },
    { name: 'Instagram', href: 'https://instagram.com/kmahesh110606' },
  ],

  skills: [
    {
      category: 'Programming & Development',
      items: [
        'React+Vite',
        'JavaScript | TypeScript',
        'HTML | CSS | TailWindCSS',
        'Flask (Python)',
        'SQLite3',
        'Django',
        'FastAPI',
        'WebSockets',
        'Bootstrap v5.3',
        'WinUI3',
        '.NET Frameworks',
        'C (Programming Language)',
        'Python (Programming Language)',
        'x86 Assembly',
      ],
    },
    {
      category: 'Design & Tools',
      items: [
        'Figma',
        'UI Design',
        'UX Design',
        'Clean UI',
        'Design Thinking',
        'Front-End Development',
        'User Interface Design',
      ],
    },
    {
      category: 'Leadership & Collaboration',
      items: [
        'Team Leadership',
        'Leadership',
        'Operations',
        'Collaboration',
        'Innovation',
        'Student Projects',
        'Tech Startups',
        'College Life',
        'University Projects',
        'Side Project',
        'Teamwork',
        'Building Together',
      ],
    },
    {
      category: 'Technical & Systems',
      items: [
        'Network Administration',
        'Group Policy',
        'Windows Server',
        'Productivity Tools',
        'Open Source',
        'Software Development',
        'Coding Life',
        'Programmers Life',
        'Frontend Engineer',
        'Tech Community',
        'Digital Innovation',
      ],
    },
    {
      category: 'Broader Interests & Tags',
      items: [
        'Web Development',
        'Frontend Development',
        'UIDesign',
        'UXDesign',
        'TechForStudents',
        'StudentInnovation',
        'CampusInnovation',
        'FutureOfTech',
        'Engineering Life',
        'BTech',
        'Learning Journey',
        'Innovation',
        'Tech Startups',
        'Tech Community',
        'Digital Innovation',
      ],
    },
  ],

  // projects - fill with your projects, links and tech stack
  projects: [
    {
      title: 'VHome',
      description:
        'A one stop gateway to all services and websites used by students of VIT Chennai',
      link: 'https://vhome.co.in',
      image: '',
      tech: ['React', 'Vite', 'TailWindCSS', 'HTML', 'CSS', 'JavaScript', 'FluentUI Icons Library',],
    },
    {
      title: 'WorkSpace OS',
      description:
        'A Cloud-Based OS that stays in the Web, accessible from wherever you are!!',
      link: '#',
      image: '',
      tech: ['Django', 'Python', 'Python-Models', 'JavaScript', 'HTML', 'CSS', 'Microsoft Azure (Hosting)'],
    },
  ],

  certifications: [
    {
      title: 'Create Your Own Chatbot Website with Open Source LLMs',
      issuer: 'CognitiveClass',
      issued: 'May 2025',
      credentialId: '2a055965ad694ac8bafd088ffcf34fea',
      document: 'Create Your Own Chatbot Website with Open Source LLMs.pdf',
      skills: ['Chatbot Development', 'Open Source LLMs'],
    },
    {
      title: 'Python (Programming Language)',
      issuer: 'IBM',
      issued: '2025',
      credentialId: '',
      document: 'IBM Python Certificate.pdf',
      skills: ['Python Programming Fundamentals'],
    },
    {
      title: 'CS50x Introduction to Computer Science',
      issuer: 'Harvard University',
      issued: 'Feb 2025',
      credentialId: '60f340bc-883b-4a0d-8e25-c3ac47211b02',
      document: 'CS50x.pdf',
      skills: ['C Programming', 'Python Programming', 'Data Structures', 'Algorithms'],
    },
    {
      title: 'C# by Microsoft and freeCodeCamp',
      issuer: 'Microsoft & freeCodeCamp',
      issued: '2025',
      credentialId: '',
      document: '',
      skills: ['C Programming', 'Computer Science fundamentals'],
    },
  ],

  education: [
    {
      institution: 'Vellore Institute of Technology (VIT Chennai)',
      degree: 'Bachelor of Technology, Computer Engineering',
      duration: 'Jul 2024 – Jul 2028',
      grade: '9.4 CGPA (Sem 1: 9.49, Sem 2: 9.43, CGPA: 9.46)',
      activities: '',
      skills: [
        'Computer Science',
        'Software Development',
        'Programming',
        'Object-Oriented Programming (OOP)',
        'Computer Engineering',
        'User Interface Design',
        'Python',
        'Java',
        'SQL',
        'Oracle SQL Developer',
        'DBMS',
        'Oracle Database',
        'Database Design & Development',
        'Data Structures',
        'Algorithms',
        'Theory of Computation',
        'Operating Systems',
        'Linux',
        'CLI',
        'Microprocessors (8051, 8086)',
        'Microcontrollers',
        'Computer Architecture & Organization',
        'Assembly Language',
        'x86 Assembly',
        'Data Networks',
        'HTML',
        'HTML5',
        'CSS',
        'CSS Flexbox',
        'JavaScript',
        'React.js',
      ],
    },
    {
      institution: 'Pace Junior Science College (PJSC Nerul)',
      degree: 'Higher Secondary',
      duration: '2022 – 2024',
      grade: '90.5%',
      activities: 'Head Boy, Student Council (2022–24)',
      skills: [
        'x86 Assembly',
        'Computer Science',
        'C++',
        'Software Development',
        'Programming',
        'Object-Oriented Programming (OOP)',
      ],
    },
    {
      institution: 'CS50x – Introduction to Computer Science (Harvard University)',
      degree: 'Coursework',
      duration: 'Jun 2024 – Feb 2025',
      grade: '',
      activities: '',
      skills: [
        'JavaScript',
        'C Programming',
        'HTML',
        'HTML5',
        'CSS',
        'Git',
        'SQLite',
        'Data Structures',
        'Algorithms',
        'Front-End Development',
        'Debugging Code',
        'Object-Oriented Programming (OOP)',
        'Python',
        'SQL',
        'Scratch',
        'Flask',
      ],
    },
    {
      institution: 'North Point School',
      degree: 'Secondary Education',
      duration: 'Mar 2018 – Jul 2022',
      grade: '98%',
      activities: '2nd place in MVCEC Coding Competition 2021 (Python)',
      skills: [
        'HTML',
        'Computer Science',
        'Microsoft Office',
        'Software Development',
        'Programming',
        'Object-Oriented Programming (OOP)',
        'Microsoft Access',
        'Java',
      ],
    },
    {
      institution: 'Queen of Angels’ Convent Higher Secondary School',
      degree: 'Schooling',
      duration: 'Mar 2016 – Mar 2018',
      grade: '',
      activities: '',
      skills: [],
    },
    {
      institution: 'North Point School (Primary Education)',
      degree: 'Primary Education',
      duration: 'Mar 2009 – Mar 2016',
      grade: '',
      activities: '',
      skills: [],
    },
  ],

  contact: {
    email: 'kmahesh110606@outlook.com',
    phone: '8591495253',
    whatsapp: '918591495253',
    note: 'Open to internships and project collaborations. Prefer email for contact.'
  }
}

export default data
